# Generated by Django 2.1.5 on 2019-02-10 00:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='food',
            name='last_modified_date',
        ),
        migrations.AddField(
            model_name='food',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='food',
            name='last_modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
