# Generated by Django 2.1.5 on 2019-02-10 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0003_auto_20190210_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='energy',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
    ]
