# Generated by Django 2.1.5 on 2019-02-10 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0004_auto_20190210_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='carbohydrate',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='food',
            name='energy',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='food',
            name='fat',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='food',
            name='fibre',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='food',
            name='protein',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='food',
            name='sodium',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
